# -*- coding: utf-8 -*-
"""Cosine similarity between two sentences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ho82E6ZwTtlEiDlVaKgcLwXGkWOTa_CR
"""

#Importing the libraries
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Vectorizing a given sentence
sentence1 = ". Liberalism advocated open trade in the economic sphere and the elimination of the limits imposed by the state on the exchange of goods and services."
sentence2 = " The concept of liberalization of in the economic sphere basically means the liberalization of market structure.  "
tokens1 = list(sentence1.lower().split())
tokens2 = list(sentence2.lower().split())
print(len(tokens1),len(tokens2))

#Creating a vocabulary for sentence1

# start indexing from 1
vocab1, index = {}, 1
# add a padding token
vocab1['<pad>'] = 0
for token in tokens1:
    if token not in vocab1: 
        vocab1[token] = index
        index += 1
vocab_size1 = len(vocab1)
print(vocab1)

#Creating a vocabulary for sentence2

# start indexing from 1
vocab2, index = {}, 1
# add a padding token
vocab2['<pad>'] = 0
for token in tokens2:
    if token not in vocab2: 
        vocab2[token] = index
        index += 1
vocab_size2 = len(vocab2)
print(vocab2)

#Vectorizing the sentence
vectorized_sentence1 = [vocab1[word] for word in tokens1]
vectorized_sentence2 = [vocab2[word] for word in tokens2]

print(vectorized_sentence1)
print(vectorized_sentence2)

from math import sqrt
def get_cosine(vector1, vector2):
    intersection = set(vector1) & set(vector2)
    numerator = sum([vector1[x] * vector2[x] for x in intersection])

   
    sum1 = sum([vector1[x] ** 2 for x in list(vector1)])
    sum2 = sum([vector2[x] ** 2 for x in list(vector2)])
    denominator = math.sqrt(sum1) * math.sqrt(sum2)

    if not denominator:
        return 0.0
    else:
        return float(numerator) / denominator

#Calculating the cosine similarity
cosine = get_cosine(vectorized_sentence1, vectorized_sentence2)
print("Cosine similarity is: ",cosine)

